import glob
import json
import os

# Carpeta donde están los archivos .arb
ARB_FOLDER = "lib/l10n"

# Traducciones para cada clave y cada idioma/variante
translations = {
     "profile": {
        "en": "My profile",
        "es": "Mi perfil",
        "es_419": "Mi perfil",
        "fr": "Mon profil",
        "pt": "Meu perfil",
        "pt_BR": "Meu perfil",
        "de": "Mein Profil",
        "it": "Il mio profilo",
        "ar": "ملفي الشخصي",
        "ja": "マイプロフィール",
        "zh": "我的资料",
        "ru": "Мой профиль",
        "ko": "내 프로필",
        "bg": "Моят профил",
        "nl": "Mijn profiel",
        "he": "הפרופיל שלי",
        "hi": "मेरा प्रोफ़ाइल",
        "el": "Το προφίλ μου",
        "hu": "Profilom",
        "pl": "Mój profil",
        "tl": "Aking profile",
        "tr": "Profilim",
        "vi": "Hồ sơ của tôi",
    },
    "profileUpdated": {
        "en": "Profile updated",
        "es": "Perfil actualizado",
        "es_419": "Perfil actualizado",
        "fr": "Profil mis à jour",
        "pt": "Perfil atualizado",
        "pt_BR": "Perfil atualizado",
        "de": "Profil aktualisiert",
        "it": "Profilo aggiornato",
        "ar": "تم تحديث الملف الشخصي",
        "ja": "プロフィールが更新されました",
        "zh": "资料已更新",
        "ru": "Профиль обновлен",
        "ko": "프로필이 업데이트되었습니다",
        "bg": "Профилът е актуализиран",
        "nl": "Profiel bijgewerkt",
        "he": "הפרופיל עודכן",
        "hi": "प्रोफ़ाइल अपडेट किया गया",
        "el": "Το προφίλ ενημερώθηκε",
        "hu": "Profil frissítve",
        "pl": "Profil zaktualizowany",
        "tl": "Na-update ang profile",
        "tr": "Profil güncellendi",
        "vi": "Hồ sơ đã được cập nhật",
    },
    "profileMyAvatar": {
        "en": "My avatar",
        "es": "Mi avatar",
        "es_419": "Mi avatar",
        "fr": "Mon avatar",
        "pt": "Meu avatar",
        "pt_BR": "Meu avatar",
        "de": "Mein Avatar",
        "it": "Il mio avatar",
        "ar": "صورتي الرمزية",
        "ja": "私のアバター",
        "zh": "我的头像",
        "ru": "Мой аватар",
        "ko": "내 아바타",
        "bg": "Моят аватар",
        "nl": "Mijn avatar",
        "he": "האווטאר שלי",
        "hi": "मेरा अवतार",
        "el": "Το avatar μου",
        "hu": "Avatárom",
        "pl": "Mój awatar",
        "tl": "Aking avatar",
        "tr": "Avatarım",
        "vi": "Hình đại diện của tôi",
    },
    "profileUser": {
        "en": "User",
        "es": "Usuario",
        "es_419": "Usuario",
        "fr": "Utilisateur",
        "pt": "Usuário",
        "pt_BR": "Usuário",
        "de": "Benutzer",
        "it": "Utente",
        "ar": "مستخدم",
        "ja": "ユーザー",
        "zh": "用户",
        "ru": "Пользователь",
        "ko": "사용자",
        "bg": "Потребител",
        "nl": "Gebruiker",
        "he": "משתמש",
        "hi": "उपयोगकर्ता",
        "el": "Χρήστης",
        "hu": "Felhasználó",
        "pl": "Użytkownik",
        "tl": "User",
        "tr": "Kullanıcı",
        "vi": "Người dùng",
    },
    "profileSpeakingStyle": {
        "en": "Speaking style",
        "es": "Estilo de habla",
        "es_419": "Estilo de habla",
        "fr": "Style de parole",
        "pt": "Estilo de fala",
        "pt_BR": "Estilo de fala",
        "de": "Sprechstil",
        "it": "Stile di parlata",
        "ar": "أسلوب الكلام",
        "ja": "話し方のスタイル",
        "zh": "说话风格",
        "ru": "Стиль речи",
        "ko": "말하기 스타일",
        "bg": "Стил на говорене",
        "nl": "Spreekstijl",
        "he": "סגנון דיבור",
        "hi": "बोलने की शैली",
        "el": "Στυλ ομιλίας",
        "hu": "Beszédstílus",
        "pl": "Styl mówienia",
        "tl": "Estilo ng pagsasalita",
        "tr": "Konuşma tarzı",
        "vi": "Phong cách nói",
    },
    "profileSpeakingStyleHint": {
        "en": "e.g. “warm and close”, “direct and concise”",
        "es": "ej. “cálido y cercano”, “directo y conciso”",
        "es_419": "ej. “cálido y cercano”, “directo y conciso”",
        "fr": "ex. « chaleureux et proche », « direct et concis »",
        "pt": "ex.: “caloroso e próximo”, “direto e conciso”",
        "pt_BR": "ex.: “caloroso e próximo”, “direto e conciso”",
        "de": "z. B. „warm und nah“, „direkt und prägnant“",
        "it": "es.: “caldo e vicino”, “diretto e conciso”",
        "ar": "مثال: \"دافئ وقريب\"، \"مباشر وموجز\"",
        "ja": "例：「温かく親しい」、「率直で簡潔」",
        "zh": "例如：“温暖而亲近”，“直接而简洁”",
        "ru": "например: «тёплый и близкий», «прямой и краткий»",
        "ko": "예: “따뜻하고 친근한”, “직접적이고 간결한”",
        "bg": "напр.: „топъл и близък“, „директен и кратък“",
        "nl": "bijv. 'warm en dichtbij', 'direct en beknopt'",
        "he": "לדוגמה: \"חמים וקרוב\", \"ישיר ותמציתי\"",
        "hi": "उदा. “गर्मजोशी और निकटता”, “सीधा और संक्षिप्त”",
        "el": "π.χ. «ζεστός και κοντινός», «άμεσος και συνοπτικός»",
        "hu": "pl.: „meleg és közvetlen”, „közvetlen és tömör”",
        "pl": "np. „ciepły i bliski”, „bezpośredni i zwięzły”",
        "tl": "hal. “mainit at malapit”, “direkta at maigsi”",
        "tr": "ör. “sıcak ve yakın”, “doğrudan ve özlü”",
        "vi": "ví dụ: “ấm áp và gần gũi”, “trực tiếp và ngắn gọn”",
    },
    "profileInterests": {
        "en": "Interests",
        "es": "Intereses",
        "es_419": "Intereses",
        "fr": "Intérêts",
        "pt": "Interesses",
        "pt_BR": "Interesses",
        "de": "Interessen",
        "it": "Interessi",
        "ar": "الاهتمامات",
        "ja": "興味",
        "zh": "兴趣",
        "ru": "Интересы",
        "ko": "관심사",
        "bg": "Интереси",
        "nl": "Interesses",
        "he": "תחומי עניין",
        "hi": "रुचियाँ",
        "el": "Ενδιαφέροντα",
        "hu": "Érdeklődések",
        "pl": "Zainteresowania",
        "tl": "Mga interes",
        "tr": "İlgi alanları",
        "vi": "Sở thích",
    },
    "profileInterestHint": {
        "en": "Add interest...",
        "es": "Añadir interés...",
        "es_419": "Añadir interés...",
        "fr": "Ajouter un intérêt...",
        "pt": "Adicionar interesse...",
        "pt_BR": "Adicionar interesse...",
        "de": "Interesse hinzufügen...",
        "it": "Aggiungi interesse...",
        "ar": "أضف اهتمامًا...",
        "ja": "興味を追加...",
        "zh": "添加兴趣...",
        "ru": "Добавить интерес...",
        "ko": "관심사 추가...",
        "bg": "Добавяне на интерес...",
        "nl": "Voeg interesse toe...",
        "he": "הוסף תחום עניין...",
        "hi": "रुचि जोड़ें...",
        "el": "Προσθήκη ενδιαφέροντος...",
        "hu": "Érdeklődés hozzáadása...",
        "pl": "Dodaj zainteresowanie...",
        "tl": "Magdagdag ng interes...",
        "tr": "İlgi ekle...",
        "vi": "Thêm sở thích...",
    },
    "profileCommonPhrases": {
        "en": "Common phrases",
        "es": "Frases comunes",
        "es_419": "Frases comunes",
        "fr": "Phrases courantes",
        "pt": "Frases comuns",
        "pt_BR": "Frases comuns",
        "de": "Gebräuchliche Sätze",
        "it": "Frasi comuni",
        "ar": "عبارات شائعة",
        "ja": "よく使うフレーズ",
        "zh": "常用短语",
        "ru": "Распространённые фразы",
        "ko": "자주 쓰는 문구",
        "bg": "Чести изрази",
        "nl": "Veelgebruikte zinnen",
        "he": "ביטויים נפוצים",
        "hi": "सामान्य वाक्यांश",
        "el": "Κοινές φράσεις",
        "hu": "Gyakori kifejezések",
        "pl": "Popularne zwroty",
        "tl": "Karaniwang parirala",
        "tr": "Yaygın ifadeler",
        "vi": "Cụm từ thường dùng",
    },
    "profileCommonPhraseHint": {
        "en": "Add common phrase...",
        "es": "Añadir frase común...",
        "es_419": "Añadir frase común...",
        "fr": "Ajouter une phrase courante...",
        "pt": "Adicionar frase comum...",
        "pt_BR": "Adicionar frase comum...",
        "de": "Gebräuchlichen Satz hinzufügen...",
        "it": "Aggiungi frase comune...",
        "ar": "أضف عبارة شائعة...",
        "ja": "よく使うフレーズを追加...",
        "zh": "添加常用短语...",
        "ru": "Добавить распространённую фразу...",
        "ko": "자주 쓰는 문구 추가...",
        "bg": "Добавяне на честа фраза...",
        "nl": "Voeg veelgebruikte zin toe...",
        "he": "הוסף ביטוי נפוץ...",
        "hi": "सामान्य वाक्यांश जोड़ें...",
        "el": "Προσθήκη κοινής φράσης...",
        "hu": "Gyakori kifejezés hozzáadása...",
        "pl": "Dodaj popularny zwrot...",
        "tl": "Magdagdag ng karaniwang parirala...",
        "tr": "Yaygın ifade ekle...",
        "vi": "Thêm cụm từ thường dùng...",
    },
    "generatingVoice": {
        "en": "Generating audio with cloned voice",
        "es": "Generando audio con voz clonada",
        "es_419": "Generando audio con voz clonada",
        "fr": "Génération de l'audio avec une voix clonée",
        "pt": "Gerando áudio com voz clonada",
        "pt_BR": "Gerando áudio com voz clonada",
        "de": "Audio mit geklonter Stimme wird erstellt",
        "it": "Generazione audio con voce clonata",
        "ar": "إنشاء صوت بصوت مستنسخ",
        "ja": "クローン音声でオーディオを生成中",
        "zh": "使用克隆语音生成音频",
        "ru": "Генерация аудио с клонированным голосом",
        "ko": "복제된 음성으로 오디오 생성 중",
        "bg": "Генериране на аудио с клониран глас",
        "nl": "Audio genereren met gekloonde stem",
        "he": "יוצר שמע עם קול משובט",
        "hi": "क्लोन की गई आवाज़ से ऑडियो बना रहा है",
        "el": "Δημιουργία ήχου με κλωνοποιημένη φωνή",
        "hu": "Hang generálása klónozott hanggal",
        "pl": "Generowanie dźwięku ze sklonowanym głosem",
        "tl": "Pagbuo ng audio gamit ang kinopyang boses",
        "tr": "Klonlanmış sesle ses oluşturuluyor",
        "vi": "Đang tạo âm thanh bằng giọng sao chép",
    },
    "generatingVideo": {
        "en": "Generating greeting with your avatar",
        "es": "Generando saludo con tu avatar",
        "es_419": "Generando saludo con tu avatar",
        "fr": "Génération d'une salutation avec votre avatar",
        "pt": "Gerando saudação com seu avatar",
        "pt_BR": "Gerando saudação com seu avatar",
        "de": "Begrüßung mit Ihrem Avatar wird erstellt",
        "it": "Generando saluto con il tuo avatar",
        "ar": "إنشاء تحية باستخدام صورتك الرمزية",
        "ja": "アバターで挨拶を生成中",
        "zh": "正在用你的头像生成问候",
        "ru": "Генерация приветствия с вашим аватаром",
        "ko": "아바타로 인사말 생성 중",
        "bg": "Генериране на поздрав с вашия аватар",
        "nl": "Begroeting genereren met je avatar",
        "he": "יוצר ברכה עם האווטאר שלך",
        "hi": "आपके अवतार से अभिवादन बना रहा है",
        "el": "Δημιουργία χαιρετισμού με το avatar σας",
        "hu": "Üdvözlés generálása az avataroddal",
        "pl": "Generowanie powitania z Twoim avatarem",
        "tl": "Pagbuo ng pagbati gamit ang iyong avatar",
        "tr": "Avatarınızla selamlama oluşturuluyor",
        "vi": "Đang tạo lời chào với avatar của bạn",
    },
    "voiceCloning": {
        "en": "Cloning Voice",
        "es": "Clonando voz",
        "es_419": "Clonando voz",
        "fr": "Clonage de la voix",
        "pt": "Clonagem de voz",
        "pt_BR": "Clonagem de voz",
        "de": "Stimme klonen",
        "it": "Clonazione vocale",
        "ar": "استنساخ الصوت",
        "ja": "声をクローン中",
        "zh": "语音克隆",
        "ru": "Клонирование голоса",
        "ko": "음성 복제",
        "bg": "Клониране на глас",
        "nl": "Stem klonen",
        "he": "שכפול קול",
        "hi": "आवाज क्लोन कर रहा है",
        "el": "Κλωνοποίηση φωνής",
        "hu": "Hang klónozása",
        "pl": "Klonowanie głosu",
        "tl": "Pag-clone ng boses",
        "tr": "Ses klonlama",
        "vi": "Sao chép giọng nói",
    },
    "voiceCloningInProgress": {
        "en": "Cloning voice in progress",
        "es": "Clonación de voz en progreso",
        "es_419": "Clonación de voz en progreso",
        "fr": "Clonage de la voix en cours",
        "pt": "Clonagem de voz em andamento",
        "pt_BR": "Clonagem de voz em andamento",
        "de": "Stimmenklonung läuft",
        "it": "Clonazione vocale in corso",
        "ar": "جارٍ استنساخ الصوت",
        "ja": "声のクローンを作成中",
        "zh": "语音克隆进行中",
        "ru": "Идёт клонирование голоса",
        "ko": "음성 복제 진행 중",
        "bg": "Клонирането на глас е в процес",
        "nl": "Stemklonen bezig",
        "he": "תהליך שכפול קול מתבצע",
        "hi": "आवाज की क्लोनिंग जारी है",
        "el": "Κλωνοποίηση φωνής σε εξέλιξη",
        "hu": "Hang klónozása folyamatban",
        "pl": "Trwa klonowanie głosu",
        "tl": "Isinasagawa ang pag-clone ng boses",
        "tr": "Ses klonlama devam ediyor",
        "vi": "Đang sao chép giọng nói",
    }
}


def get_locale_from_filename(filename):
    base = os.path.basename(filename)
    # Ejemplo: app_es_419.arb o app_en.arb
    parts = base.replace('.arb', '').split('_')
    if len(parts) == 3:
        return f"{parts[1]}_{parts[2]}"
    elif len(parts) == 2:
        return parts[1]
    else:
        return "en"

for filename in glob.glob(f"{ARB_FOLDER}/*.arb"):
    with open(filename, "r", encoding="utf-8") as f:
        data = json.load(f)

    locale = data.get("@@locale") or get_locale_from_filename(filename)
    # Normalizar pt-BR, es-419, etc.
    locale = locale.replace("-", "_")

    updated = False

    for key, lang_dict in translations.items():
        # Buscar traducción por código exacto, luego por idioma base
        value = lang_dict.get(locale) or lang_dict.get(locale.split("_")[0])
        if value:
            if key not in data or data[key] != value:
                data[key] = value
                updated = True
                print(f"{filename}: clave '{key}' agregada/actualizada")


    if updated:
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

print("¡Listo! Revisa los archivos .arb actualizados.")
